"""Tk layout and styling; all behavior is supplied by the application."""
import tkinter as tk
from tkinter import ttk


def build_widgets(view):
    style = ttk.Style(view)
    style.theme_use("clam")
    style.configure("TFrame", background="#f4f6f8")
    style.configure("TLabel", background="#f4f6f8", foreground="#243447", font=("Yu Gothic UI", 10))
    style.configure("Title.TLabel", font=("Yu Gothic UI", 21, "bold"))
    style.configure("Muted.TLabel", foreground="#526276")
    style.configure("TButton", font=("Yu Gothic UI", 10), padding=(12, 8))
    style.configure("Primary.TButton", background="#1767ce", foreground="white", font=("Yu Gothic UI", 11, "bold"))
    style.map("Primary.TButton", background=[("disabled", "#d5dce5"), ("active", "#1255ab")], foreground=[("disabled", "#526276")])
    style.configure("Card.TFrame", background="white")
    style.configure("Card.TLabel", background="white")
    style.configure("CardMuted.TLabel", background="white", foreground="#526276")
    style.configure("TEntry", padding=7, font=("Yu Gothic UI", 10))
    style.configure("Treeview", rowheight=28, font=("Yu Gothic UI", 10))
    style.configure("Treeview.Heading", font=("Yu Gothic UI", 10, "bold"))
    body = ttk.Frame(view, padding=24)
    body.pack(fill="both", expand=True)
    header = ttk.Frame(body)
    header.pack(fill="x")
    ttk.Label(header, text=view.title(), style="Title.TLabel").pack(side="left")
    view.clear_btn = ttk.Button(header, text="一覧をクリア", command=view.clear_jobs)
    view.clear_btn.pack(side="right")
    ttk.Label(body, text="ZIP・7z・RAR・TAR  /  複数ファイルをまとめて解凍", style="Muted.TLabel").pack(anchor="w", pady=(4, 16))
    view.drop_area = tk.Frame(body, bg="white", highlightbackground="#b7c8dd", highlightthickness=1, pady=16)
    view.drop_area.pack(fill="x")
    view.drop_title = tk.Label(view.drop_area, text="ここにファイルをドロップ", bg="white", fg="#243447", font=("Yu Gothic UI", 14, "bold"))
    view.drop_title.pack(pady=(0, 6))
    view.dnd_hint = tk.Label(view.drop_area, text="複数の書庫も、そのまま追加できます", bg="white", fg="#526276", font=("Yu Gothic UI", 10))
    view.dnd_hint.pack()
    view.choose_btn = ttk.Button(view.drop_area, text="ファイルを選ぶ", command=view.choose_archive)
    view.choose_btn.pack(pady=(10, 0))
    view.card_region = ttk.Frame(body)
    view.card_region.pack(fill="both", expand=True, pady=(16, 8))
    view.canvas = tk.Canvas(view.card_region, bg="#f4f6f8", highlightthickness=0, height=1)
    scroll = ttk.Scrollbar(view.card_region, command=view.canvas.yview)
    view.canvas.configure(yscrollcommand=scroll.set)
    scroll.pack(side="right", fill="y")
    view.canvas.pack(side="left", fill="both", expand=True)
    view.card_list = ttk.Frame(view.canvas)
    view._card_window = view.canvas.create_window(0, 0, window=view.card_list, anchor="nw")
    view.card_list.bind("<Configure>", lambda _e: view.canvas.configure(scrollregion=view.canvas.bbox("all")))
    view.canvas.bind("<Configure>", lambda e: view.canvas.itemconfigure(view._card_window, width=e.width))
    view.bind("<MouseWheel>", lambda e: view.canvas.yview_scroll(-int(e.delta / 120), "units"))
    view.options = ttk.Frame(body)
    view.options.pack(fill="x")
    dest_row = ttk.Frame(view.options)
    dest_row.pack(fill="x")
    ttk.Label(dest_row, text="保存先").pack(side="left", padx=(0, 10))
    view.dest_entry = ttk.Entry(dest_row, textvariable=view.dest_var)
    view.dest_entry.pack(side="left", fill="x", expand=True)
    view.dest_btn = ttk.Button(dest_row, text="変更", command=view.choose_dest)
    view.dest_btn.pack(side="left", padx=(8, 0))
    ttk.Label(view.options, text="書庫ごとのフォルダに保存。同名の場合は連番で作成します。", style="Muted.TLabel").pack(anchor="w", pady=(6, 8))
    view.pw_frame = ttk.Frame(view.options)
    ttk.Label(view.pw_frame, text="パスワード").pack(side="left", padx=(0, 10))
    view.pw_entry = ttk.Entry(view.pw_frame, textvariable=view.password_var, show="●")
    view.pw_entry.pack(side="left", fill="x", expand=True)
    view.pw_entry.bind("<Return>", lambda _e: view.start_extract())
    ttk.Checkbutton(view.pw_frame, text="表示", variable=view.show_password,
                    command=lambda: view.pw_entry.configure(show="" if view.show_password.get() else "●")).pack(side="left", padx=(8, 0))
    view.details_btn = ttk.Button(body, text="内容を見る", command=view.toggle_details)
    view.details_btn.pack(anchor="w", pady=(8, 0))
    view.details = ttk.Frame(body)
    view.tree = ttk.Treeview(view.details, columns=("size",), show="tree headings", height=5)
    view.tree.heading("#0", text="フォルダ / ファイル")
    view.tree.heading("size", text="サイズ")
    view.tree.column("size", width=100, anchor="e", stretch=False)
    tree_scroll = ttk.Scrollbar(view.details, command=view.tree.yview)
    view.tree.configure(yscrollcommand=tree_scroll.set)
    view.tree.pack(side="left", fill="both", expand=True)
    tree_scroll.pack(side="right", fill="y")
    view.footer = ttk.Frame(body)
    view.footer.pack(fill="x", pady=(16, 0))
    view.extract_btn = ttk.Button(view.footer, text="解凍する", style="Primary.TButton", command=view.start_extract, state="disabled")
    view.extract_btn.pack(side="right")
    view.cancel_btn = ttk.Button(view.footer, text="キャンセル", command=view.cancel_extract, state="disabled")
    view.cancel_btn.pack(side="right", padx=(0, 8))
    view.status_label = ttk.Label(body, textvariable=view.status, wraplength=650)
    view.status_label.pack(fill="x", pady=(8, 0))
    view.bind("<Configure>", view._resize_text)

