"""Tk layout and styling; all behavior is supplied by the application."""
import tkinter as tk
from tkinter import ttk
from version import VERSION


def build_widgets(view):
    style = ttk.Style(view)
    style.theme_use("clam")
    style.configure("TFrame", background="#f4f6f8")
    style.configure("TLabel", background="#f4f6f8", foreground="#243447", font=("Yu Gothic UI", 10))
    style.configure("Title.TLabel", font=("Yu Gothic UI", 21, "bold"))
    style.configure("Muted.TLabel", foreground="#526276")
    style.configure("TButton", font=("Yu Gothic UI", 10), padding=(12, 8))
    style.configure("Primary.TButton", background="#1767ce", foreground="white", font=("Yu Gothic UI", 11, "bold"))
    style.map("Primary.TButton", background=[("disabled", "#d5dce5"), ("active", "#1255ab")], foreground=[("disabled", "#526276")])
    style.configure("Card.TFrame", background="white")
    style.configure("Card.TLabel", background="white")
    style.configure("CardMuted.TLabel", background="white", foreground="#526276")
    style.configure("TEntry", padding=7, font=("Yu Gothic UI", 10))
    style.configure("Treeview", rowheight=28, font=("Yu Gothic UI", 10))
    style.configure("Treeview.Heading", font=("Yu Gothic UI", 10, "bold"))
    body = ttk.Frame(view, padding=24)
    body.pack(fill="both", expand=True)
    header = ttk.Frame(body)
    header.pack(fill="x")
    ttk.Label(header, text=view.title(), style="Title.TLabel").pack(side="left")
    view.clear_btn = ttk.Button(header, text="一覧をクリア", command=view.clear_jobs)
    view.clear_btn.pack(side="right")
    view.update_btn = ttk.Button(header, text='更新を確認', command=view.check_updates)
    view.update_btn.pack(side='right', padx=(0, 8))
    view.update_text = tk.StringVar(value=f'ZIP・7z・RAR・TAR  /  v{VERSION}')
    ttk.Label(body, textvariable=view.update_text, style='Muted.TLabel').pack(anchor='w', pady=(4, 8))
    view.steps_frame = ttk.Frame(body)
    view.steps_frame.pack(fill="x", pady=(0, 8))
    view.step_labels = []
    for i, text in enumerate(("① 書庫を追加", "② 内容を確認", "③ 解凍する")):
        lbl = tk.Label(view.steps_frame, text=text, bg="#f4f6f8", fg="#94a3b8",
                       font=("Yu Gothic UI", 10, "bold"))
        lbl.pack(side="left")
        view.step_labels.append(lbl)
        if i < 2:
            tk.Label(view.steps_frame, text="  →  ", bg="#f4f6f8", fg="#94a3b8",
                     font=("Yu Gothic UI", 10)).pack(side="left")
    view.drop_area = tk.Frame(body, bg="white", highlightbackground="#b7c8dd", highlightthickness=1, pady=16)
    view.drop_area.pack(fill="x")
    view.drop_title = tk.Label(view.drop_area, text="ここにファイルをドロップ", bg="white", fg="#243447", font=("Yu Gothic UI", 14, "bold"))
    view.drop_title.pack(pady=(0, 6))
    view.dnd_hint = tk.Label(view.drop_area, text="複数の書庫も、そのまま追加できます", bg="white", fg="#526276", font=("Yu Gothic UI", 10))
    view.dnd_hint.pack()
    view.choose_btn = ttk.Button(view.drop_area, text="ファイルを選ぶ", command=view.choose_archive)
    view.choose_btn.pack(pady=(10, 0))
    view.card_region = ttk.Frame(body)
    view.card_region.pack(fill="both", expand=True, pady=(16, 8))
    view.canvas = tk.Canvas(view.card_region, bg="#f4f6f8", highlightthickness=0, height=1)
    scroll = ttk.Scrollbar(view.card_region, command=view.canvas.yview)
    view.canvas.configure(yscrollcommand=scroll.set)
    scroll.pack(side="right", fill="y")
    view.canvas.pack(side="left", fill="both", expand=True)
    view.card_list = ttk.Frame(view.canvas)
    view._card_window = view.canvas.create_window(0, 0, window=view.card_list, anchor="nw")
    view.card_list.bind("<Configure>", lambda _e: view.canvas.configure(scrollregion=view.canvas.bbox("all")))
    view.canvas.bind("<Configure>", lambda e: view.canvas.itemconfigure(view._card_window, width=e.width))
    view.bind("<MouseWheel>", lambda e: view.canvas.yview_scroll(-int(e.delta / 120), "units"))
    view.options = ttk.Frame(body)
    view.options.pack(fill="x")
    dest_row = ttk.Frame(view.options)
    dest_row.pack(fill="x")
    ttk.Label(dest_row, text="保存先").pack(side="left", padx=(0, 10))
    view.dest_entry = ttk.Entry(dest_row, textvariable=view.dest_var)
    view.dest_entry.pack(side="left", fill="x", expand=True)
    view.dest_btn = ttk.Button(dest_row, text="変更", command=view.choose_dest)
    view.dest_btn.pack(side="left", padx=(8, 0))
    ttk.Label(view.options, text="書庫ごとのフォルダに保存。同名の場合は連番で作成します。", style="Muted.TLabel").pack(anchor="w", pady=(6, 8))
    view.footer = ttk.Frame(body)
    view.footer.pack(fill="x", pady=(16, 0))
    view.extract_btn = ttk.Button(view.footer, text="解凍する", style="Primary.TButton", command=view.start_extract, state="disabled")
    view.extract_btn.pack(side="right")
    view.cancel_btn = ttk.Button(view.footer, text="キャンセル", command=view.cancel_extract, state="disabled")
    view.cancel_btn.pack(side="right", padx=(0, 8))
    view.overall_frame = ttk.Frame(view.footer)
    view.overall_label = ttk.Label(view.overall_frame, text="")
    view.overall_label.pack(side="left", padx=(0, 8))
    view.overall_bar = ttk.Progressbar(view.overall_frame, mode="determinate", length=160)
    view.overall_bar.pack(side="left")
    view.status_label = ttk.Label(body, textvariable=view.status, wraplength=650)
    view.status_label.pack(fill="x", pady=(8, 0))
    view.bind("<Configure>", view._resize_text)

